### ISSUE TITLE
Define new schema for WITSML to KUDU

### ISSUE THREAD

**Issue by vilasdeshmukh** [hashmapinc/Timeseries#132]
The KUDU schema for WITSML contain objects such as well, wellbore, rig, trajectory, message, depth log, and time log. All of these objects should be revised to achieve:
1) Use "name" fields instead of "id" fields. For example, instead of uidWell, use nameWell.
2) Point# 1 also implies that the primary key definition will use "name" field instead of "id" field.
3) Make sure that the hierarchy of fields in primary key definition is "intuitive". For example, the primary key for wellbore should be "nameWell, nameWellbore" and not "nameWellbore, nameWell".
4) Depth log will have depthString as the last key field and the depth itself should be a double and not a string.

**Comment by cherrera2001** [comment]
This issue was moved to hashmapinc/Tempus#44
