### ISSUE TITLE
Create a NIFI Processor called AttributesToThingsboardDevice

### ISSUE THREAD

**Issue by vilasdeshmukh** [hashmapinc/Timeseries#133]
Rename / enhance JSONConverter nifi processor to publish attributes to thingsboard via MQTT gateway. The input and output are defined below:
INPUT:
	Device Name: (required and single name)
	Attributes: (list of comma separated attribute names)
publishing structure:
	{ 
		"value of device name attribute" : [
			"attribute name": "attribute value"
		]
	}

**Comment by cherrera2001** [comment]
This issue was moved to hashmapinc/Tempus#43
