### ISSUE TITLE
Trajectory data - new Cassandra Dao support for time and depth series

### ISSUE THREAD

**Issue by vilasdeshmukh** [hashmapinc/Timeseries#147]
Trajectory data has a lot more fields than a regular time or depth series. Therefore, the following is required to be done:
1) Define new topics for both time and depth series for MQTT
2) Create a Dao to ensure that a JSON object can be stored as a value of a time or depth series record.

**Comment by cherrera2001** [comment]
This issue was moved to hashmapinc/Tempus#31
