### ISSUE TITLE
Containerize Computation on Kafka Consumer data

### ISSUE THREAD

**Issue by ed3766** [hashmapinc/Timeseries#162]
There needs to be a docker image with for a Java Kafka Client to reads numeric data from a Kafka topic are does a simple computation (add 2 numbers).

Acceptance Criteria:
The project is mavenized and documented
The Kaka cluster is external and its configuration (topic name, broker URI, etc...)  are define as properites to the container.
Provide an interface to abstract the computation imlemenation.

**Comment by cherrera2001** [comment]
This issue was moved to hashmapinc/Tempus#16
