### ISSUE TITLE
Containerize transmission of SAX computation results to MQTT

### ISSUE THREAD

**Issue by ed3766** [hashmapinc/Timeseries#164]
Update the docker container to The MQTT transmission of results back to thingsboard (including the api key and the gateway token), the Kafka client that will subscribe and receive the data.

Acceptance Criteria:
The project is mavenized and documented
The MQTT Broker is external and its configuration (topic name, broker URI, etc...)  are define as properites to the container.

**Comment by cherrera2001** [comment]
This issue was moved to hashmapinc/Tempus#14
