### ISSUE TITLE
Create TimeSeriesDataRecord Velocity Template

### ISSUE THREAD

**Issue by ed3766** [hashmapinc/Timeseries#170]
Create a TimeSeriesDataRecord Velocity Template that writes the following JSON:

{
   "type": "record",
   "name": "TimeSeriesDataRecord",
   "fields": [
     {
       "name": "<tag_name1>",
       "ts": "2018-02-07T16:34:41.636",
       "value": "<tag_value1>"
     },     {
       "name": "<tag_name2>",
       "ts": "2018-02-07T16:34:41.636",
       "value": "<tag_value2>"
     },   ...   {
       "name": "<tag_nameN>",
       "ts": "2018-02-07T16:34:41.636",
       "value": "<tag_valueN>"
     }

  ]
}

**Comment by cherrera2001** [comment]
This issue was moved to hashmapinc/Tempus#6
